//
//  BloodDonetorApp.swift
//  
//
//  Created by Fardin Likhon on 20/4/26.
//


import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
import 'firebase_options.dart'; // Generated by flutterfire configure
import 'screens/splash_screen.dart';
import 'core/app_theme.dart';

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);
  runApp(const BloodDonetorApp());
}

class BloodDonetorApp extends StatelessWidget {
  const BloodDonetorApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      title: 'Blood Donor BD',
      theme: AppTheme.light(),
      home: const SplashScreen(),
    );
  }
}