// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJEBhlRijsjqKIm-p5yLOzBYJUKv4-sjE',
    appId: '1:302240715858:web:07261d48ad4307a846bb8b',
    messagingSenderId: '302240715858',
    projectId: 'blood-donor-app-e3979',
    authDomain: 'blood-donor-app-e3979.firebaseapp.com',
    storageBucket: 'blood-donor-app-e3979.firebasestorage.app',
    measurementId: 'G-G4EJKXXL10',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDXeK5qAfZcbSyf6_DBJhmt4KduzZfstrE',
    appId: '1:302240715858:android:a4a4a78d2e262cbb46bb8b',
    messagingSenderId: '302240715858',
    projectId: 'blood-donor-app-e3979',
    storageBucket: 'blood-donor-app-e3979.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBrrqGkbnOKkVRsMramPceesG0VOh2sf98',
    appId: '1:302240715858:ios:d2a446ed40c4872e46bb8b',
    messagingSenderId: '302240715858',
    projectId: 'blood-donor-app-e3979',
    storageBucket: 'blood-donor-app-e3979.firebasestorage.app',
    iosClientId: '302240715858-67gd6s6nrqjgi5p3q68ab5m18frsodpo.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBrrqGkbnOKkVRsMramPceesG0VOh2sf98',
    appId: '1:302240715858:ios:d2a446ed40c4872e46bb8b',
    messagingSenderId: '302240715858',
    projectId: 'blood-donor-app-e3979',
    storageBucket: 'blood-donor-app-e3979.firebasestorage.app',
    iosClientId: '302240715858-67gd6s6nrqjgi5p3q68ab5m18frsodpo.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAJEBhlRijsjqKIm-p5yLOzBYJUKv4-sjE',
    appId: '1:302240715858:web:7634fb859a4ef91246bb8b',
    messagingSenderId: '302240715858',
    projectId: 'blood-donor-app-e3979',
    authDomain: 'blood-donor-app-e3979.firebaseapp.com',
    storageBucket: 'blood-donor-app-e3979.firebasestorage.app',
    measurementId: 'G-PJKLD5G4ZT',
  );

}